// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework DZToolFrame
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ProductStructureUI",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
