// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// DZToolCommandProductAttr.h
// The state chart based command: DZToolCommandProductAttr
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef DZToolCommandProductAttr_H
#define DZToolCommandProductAttr_H

#include "CATStateCommand.h"
#include "CATBoolean.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class DZToolCommandProductAttr: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( DZToolCommandProductAttr, CATStateCommand )

  public:

  DZToolCommandProductAttr();
  virtual ~DZToolCommandProductAttr();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

  private:
};

//----------------------------------------------------------------------

#endif
