// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// DZToolDialogProductAttr.h
// The dialog : DZToolDialogProductAttr
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef DZToolDialogProductAttr_H
#define DZToolDialogProductAttr_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class DZToolDialogProductAttr: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( DZToolDialogProductAttr, CATDlgDialog )

  public:

  DZToolDialogProductAttr();
  virtual ~DZToolDialogProductAttr();

  void Build ();


  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION

//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
