F:\DZ\DZTool\.\DZToolFrame\various\intel_a\HList\PrivateInterfaces.hl
F:\DZ\DZTool\.\DZToolFrame\various\intel_a\HList\ProtectedInterfaces.hl
F:\DZ\DZTool\.\DZToolFrame\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\AdvancedMathematics\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\AdvancedMathematics\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ApplicationFrame\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ApplicationFrame\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\AutomationInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\AutomationInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\BatchInfrastructure\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\BatchInfrastructure\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CAT3DXmlInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CAT3DXmlInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATDataCompatibilityInfra\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATDataCompatibilityInfra\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATGraphicProperties\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATGraphicProperties\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATIAApplicationFrame\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATIAApplicationFrame\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATIADataBasics\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATIADataBasics\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATIADataMacFortran\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATIADataMacFortran\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATImmWtpInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATImmWtpInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATJavaBridge\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATJavaBridge\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATPDMBaseInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATPDMBaseInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATPLMDictionary\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATPLMDictionary\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATSmarTeamIntegInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATSmarTeamIntegInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATSubdivisionApproximation\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATSubdivisionApproximation\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATSubdivisionMeshOperators\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATSubdivisionMeshOperators\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATSubdivisionObjects\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATSubdivisionObjects\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATTechnologicalPackageUIItf\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATTechnologicalPackageUIItf\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATV4System\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATV4System\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATVirtualVaultSystem\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATVirtualVaultSystem\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\CATXDocLinkInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\CATXDocLinkInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Communications\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Communications\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ComponentsCatalogsInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ComponentsCatalogsInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Dialog\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Dialog\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\DialogEngine\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\DialogEngine\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\FileMenu\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\FileMenu\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\GenericNaming\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\GenericNaming\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\GeometricObjects\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\GeometricObjects\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\GeometricObjectsCGM\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\GeometricObjectsCGM\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\GeometricOperators\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\GeometricOperators\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Graph\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Graph\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\HLRBase\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\HLRBase\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\InfInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\InfInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\InteractiveInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\InteractiveInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\KnowledgeInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\KnowledgeInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\KnowledgeModeler\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\KnowledgeModeler\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\LiteralFeatures\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\LiteralFeatures\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\LiteralsEditor\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\LiteralsEditor\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Mainwin\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Mainwin\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Mathematics\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Mathematics\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\MecModInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\MecModInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Multimedia\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Multimedia\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\NewTopologicalObjects\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\NewTopologicalObjects\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerBase\various\intel_a\HList\PrivateInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerBase\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerBase\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerBaseUI\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerBaseUI\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerCATIA\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerCATIA\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerCollection\various\intel_a\HList\PrivateInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerCollection\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerCollection\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerNavigator\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerNavigator\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerSystem\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectModelerSystem\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ObjectSpecsModeler\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ObjectSpecsModeler\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PolygonalTools\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PolygonalTools\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PolyhedralInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PolyhedralInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PolyhedralMathematics\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PolyhedralMathematics\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PolyhedralObjects\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PolyhedralObjects\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PolyhedralOperators\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PolyhedralOperators\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PolyhedralVisualization\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PolyhedralVisualization\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Print\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Print\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\PrintBase\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\PrintBase\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ProductStructure\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ProductStructure\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ProductStructureInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ProductStructureInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\ProductStructureUI\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\ProductStructureUI\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\SketcherInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\SketcherInterfaces\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\SpecialAPI\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\SpecialAPI\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\System\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\System\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Tessellation\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Tessellation\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\VBA\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\VBA\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\Visualization\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\Visualization\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\VisualizationBase\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\VisualizationBase\various\intel_a\HList\PublicInterfaces.hl
F:\CATIAV5R19\.\XMLParser\various\intel_a\HList\ProtectedInterfaces.hl
F:\CATIAV5R19\.\XMLParser\various\intel_a\HList\PublicInterfaces.hl
