// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// DZToolComponent.cpp
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "DZToolComponent.h"

#include "CATCreateWorkshop.h"
#include "CATCommandHeader.h"
#include "CATIWorkbenchAddin.h"

MacDeclareHeader(DZToolComponentHeader);

CATImplementClass(DZToolComponent,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 


//-----------------------------------------------------------------------------
// DZToolComponent : constructor
//-----------------------------------------------------------------------------
DZToolComponent::DZToolComponent():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// DZToolComponent : destructor
//-----------------------------------------------------------------------------
DZToolComponent::~DZToolComponent()
{
}
//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateCommands
//-----------------------------------------------------------------------------
void DZToolComponent::CreateCommands ()
{
  //命令头
  new DZToolComponentHeader
    ("DZToolHeaderProductAttr",
    "DZToolModuleProductAttr",
    "DZToolCommandProductAttr",
    (void*) NULL);
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateToolbars
//-----------------------------------------------------------------------------
CATCmdContainer * DZToolComponent::CreateToolbars ()
{
	CATCmdContainer *pCATCmdContainer=NULL;

	//添命令
	NewAccess(CATCmdStarter, pCommandProductAttr, DZToolHeaderProductAttr);
	SetAccessCommand(pCommandProductAttr, "DZToolHeaderProductAttr");

	//创建工具条
	NewAccess(CATCmdContainer, pContainerToolbar, DZToolbar);

	SetAccessChild(pContainerToolbar, pCommandProductAttr);
	CATCmdAccess *pCATCmdAccess = pCommandProductAttr;

	int visibleFlag = 1;
	//设置工具条状态
	AddToolbarView (pContainerToolbar, visibleFlag, Left);
	pCATCmdContainer=pContainerToolbar;

	return pCATCmdContainer;
}

//TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(DZToolComponent);


//Methods implementation

