set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="D:\RADER19\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=D:\RADER19\intel_a
set ADL_SITE_NAME=V5R19_B19
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=D:\RADER19\intel_a\code\command
set ADSK_CLM_WPAD_PROXY_CHECK=FALSE
set ALLUSERSPROFILE=C:\ProgramData
set APPCODE_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\appcode.vmoptions
set APPDATA=C:\Users\Administrator\AppData\Roaming
set asl.log=Destination=file
set BLD_HOST_OS=win_b64
set ChocolateyInstall=C:\ProgramData\chocolatey
set ChocolateyLastPathUpdate=133330394179836080
set CLion=D:\DZR\clion\CLion 2022.1.2\bin;
set CLION_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\clion.vmoptions
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=WIN-ARM5TUU9E3C
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DATAGRIP_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\datagrip.vmoptions
set DATASPELL_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\dataspell.vmoptions
set DEVECOSTUDIO_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\devecostudio.vmoptions
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSarMakerROOT_PATH=D:\RADER19\CATWebDSarMaker
set GATEWAY_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\gateway.vmoptions
set GoLand=D:\DZR\Goland2022.2\GoLand 2022.1.2\bin;
set GOLAND_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\goland.vmoptions
set GOPATH=D:\Code\PRO
set GOROOT=D:\DZR\go
set HOMEDRIVE=C:
set HOMEPATH=\Users\Administrator
set IDEA_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\idea.vmoptions
set IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAMBdIFH+k40WxkoCK8szsvwQAAAACAAAAAAAQZgAAAAEAACAAAADuCKTUqDmI4YNbSVS3YuFCq3L1LoFC84MfhrZuB0K+jgAAAAAOgAAAAAIAACAAAAAiPC9tfOdm6FNQjy9yJ5fOiUmPChcp+qxEMyiwowBJuWAAAACFke8RfgDqXhp4fyNuuYhfydLP+6HF3E48K100Xri2JJaIOozbLIzJdu3w8Zx3g8K5qcIoFhhueAaXzBep/1ucSRleGmHDE1VbXzMy8P+ZjhnNgUVkyzJANtOy2hxX2fFAAAAAM9HywxDrvh3Jxo3L8xzbALKNroedopYbRtmh8MPNzibIGu/DgRYMxExL1q/Z5TC3Li/M6ruoQzLWicmM2cA8aA==
set INCLUDE=D:\RADER19\intel_a\.\tools\include\win_b64;D:\RADER19\intel_a\.\tools\include;D:\DZS\vs2005\VC\include;D:\DZS\vs2005\VC\atlmfc\include;D:\DZS\vs2005\VC\PlatformSDK\include
set JETBRAINSCLIENT_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\jetbrainsclient.vmoptions
set JETBRAINS_CLIENT_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\jetbrains_client.vmoptions
set JLMDeployROOT_PATH=D:\RADER19\intel_a\jlm\jlmdeploy65
set KMP_BLOCKTIME=0
set LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;D:\DZS\vs2005\VC\lib\amd64;D:\DZS\vs2005\VC\atlmfc\lib\amd64;D:\DZS\vs2005\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\Administrator\AppData\Local
set LOGONSERVER=\\WIN-ARM5TUU9E3C
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=D:\RADER19\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=D:\RADER19\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=21901
set MkmkDictionary_PATH=D:\RADER19\intel_a\.\code\dictionary
set MkmkIC_PATH=D:\RADER19\intel_a\.\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=D:\RADER19
set MkmkMsgCatalog_PATH=D:\RADER19\intel_a\.\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=D:\DZS\vs2005\VC\include;D:\DZS\vs2005\VC\atlmfc\include;D:\DZS\vs2005\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=D:\DZS\vs2005\VC\lib\amd64;D:\DZS\vs2005\VC\atlmfc\lib\amd64;D:\DZS\vs2005\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=D:\DZS\vs2005\VC\bin\amd64
set MkmkMSVCDIR=D:\DZS\vs2005\VC
set MkmkMSVCDIR_80=D:\DZS\vs2005\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=D:\DZS\vs2005\Common7\Tools\Bin;D:\DZS\vs2005\Common7\IDE
set MkmkMSVSBINDIR=D:\DZS\vs2005\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=D:\RADER19\intel_a\.\reffiles
set MkmkRMSSDK_PATH=D:\RADER19\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=D:\RADER19\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=D:\RADER19\intel_a\code\bin
set mkmkvers=mkmk Version 2.19.1
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=554
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=D:\RADER19\intel_a\code\command\
set NUMBER_OF_PROCESSORS=16
set OMP_WAIT_POLICY=PASSIVE
set OneDrive=C:\Users\Administrator\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=D:\DZS\vs2005\VC\bin\amd64;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;D:\DZS\vs2005\Common7\Tools\Bin;D:\DZS\vs2005\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Ms\git\Git\cmd;C:\Program Files\MySQL\MySQL Server 5.7\bin;D:\DZR\redis\;D:\DZR\go\bin;D:\DZR\protoc-21.1-win64\bin;C:\Program Files\PowerShell\7;D:\DZR\MinGW\bin;D:\DZR\py3.9;D:\DZR\py3.9\Scripts;D:\DZR\node\;C:\ProgramData\chocolatey\bin;D:\DZR\node;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\Code\PRO\bin;D:\DZR\go\bin;C:\Users\Administrator\go\bin;D:\DZR\Goland2022.2\GoLand 2022.1.2\bin;D:\DZR\clion\CLion 2022.1.2\bin;D:\DZR\vscode\Microsoft VS Code\bin;D:\DZR\PyCharm_2023.1.2\PyCharm 2023.1.2\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\.dotnet\tools;D:\RADER19\intel_a\TCK\command;D:\RADER19\intel_a\code\command;D:\RADER19\intel_a\code\command;D:\RADER19\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PHPSTORM_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\phpstorm.vmoptions
set POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Home China
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=8d01
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set PyCharm=D:\DZR\PyCharm_2023.1.2\PyCharm 2023.1.2\bin;
set PYCHARM_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\pycharm.vmoptions
set QT_QPA_PLATFORM_PLUGIN_PATH=D:\DZR\py3k\Lib\site-packages\PyQt5\Qt5\plugins
set RADECATSettingPath=C:\Users\Administrator\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=D:\RADER19\intel_a
set RIDER_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\rider.vmoptions
set rtcode=0
set RUBYMINE_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\rubymine.vmoptions
set SESSIONNAME=Console
set STUDIO_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\studio.vmoptions
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2023/08/13-20:48:40
set TCK_ID=V5R19_B19
set TCK_INSTALL_PATH=D:\RADER19
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R19_B19
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=D:\RADER19\intel_a
set TCK_TMP_FILE=C:\Users\ADMINI~1\AppData\Local\Temp\tckexec__Administrator_40099.bat
set TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMPFILE=\adl_unset_39980.bat
set USERDOMAIN=WIN-ARM5TUU9E3C
set USERDOMAIN_ROAMINGPROFILE=WIN-ARM5TUU9E3C
set USERNAME=Administrator
set USERPROFILE=C:\Users\Administrator
set VBTtmp=C:\Users\ADMINI~1\AppData\Local\Temp
set VS80COMNTOOLS=D:\DZS\vs2005\Common7\Tools\
set WEBIDE_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\webide.vmoptions
set WEBSTORM_VM_OPTIONS=D:\DZR\Win\win\jetbra\vmoptions\webstorm.vmoptions
set WecVersionForRosebud.634=2
set windir=C:\Windows
set ZES_ENABLE_SYSMAN=1
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
