// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// DZToolComponent.h
// Provide implementation to interface
//    CATIPRDWorkshopAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIPRDWorkshopAddin

//End CAA2 Wizard Generation Report
//
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef DZToolComponent_H
#define DZToolComponent_H

#include "CATBaseUnknown.h"
#include "CATCmdContainer.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIPRDWorkshopAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class DZToolComponent: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     DZToolComponent ();
     virtual ~DZToolComponent ();

	      /**
     * Implements a function from an interface.
     * @href CATIWorkbenchAddin#CreateCommands
     */
     void CreateCommands () ;

	      /**
     * Implements a function from an interface.
     * @href CATIWorkbenchAddin#CreateToolbars
     */
     CATCmdContainer * CreateToolbars () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  DZToolComponent (DZToolComponent &);
  DZToolComponent& operator=(DZToolComponent&);

};

//-----------------------------------------------------------------------

#endif
