// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// DZToolDialogProductAttr.cpp
// The dialog : DZToolDialogProductAttr
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "DZToolDialogProductAttr.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef DZToolDialogProductAttr_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
DZToolDialogProductAttr::DZToolDialogProductAttr() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"DZToolDialogProductAttr",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION

//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
DZToolDialogProductAttr::~DZToolDialogProductAttr()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION

//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void DZToolDialogProductAttr::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

