// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// DZToolCommandProductAttr.cpp
// The state chart based command: DZToolCommandProductAttr
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Aug 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "DZToolCommandProductAttr.h"
#include "DZToolDialogProductAttr.h"

#include "CATCreateExternalObject.h"
CATCreateClass( DZToolCommandProductAttr);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
DZToolCommandProductAttr::DZToolCommandProductAttr() :
  CATStateCommand ("DZToolCommandProductAttr", CATDlgEngOneShot, CATCommandModeExclusive) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
{
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
DZToolCommandProductAttr::~DZToolCommandProductAttr()
{
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void DZToolCommandProductAttr::BuildGraph()
{
  // TODO: Define the StateChart 
  // ---------------------------
	DZToolDialogProductAttr *pDZToolDialogProductAttr = new DZToolDialogProductAttr();
	pDZToolDialogProductAttr->Build();
	pDZToolDialogProductAttr->SetVisibility(CATDlgShow);
}
